version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: EVE_Market_Redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=123456

volumes:
  redis_data: